import checkoutFormModel from './checkoutFormModel';
const {
  formField: {
    firstName,
    lastName,
     email,
     password,
     recaptcha,
     checkbox,
     address1,
     address2,
     city,
     zipcode,
     country,
     mobile,
     countrycode,
     state,
     otp,
     file,
     date,
     file2,
     file3,
     choose,
     terms,
     licence
  }
} = checkoutFormModel;
export default {
    [firstName.name]: '',
    [lastName.name]: '',
    [email.name]: '',
    [password.name]: '',
    [otp.name]: '',
    // [recaptcha]: false,
    [checkbox.name]: false,
    [city.name]: '',
    [zipcode.name]: '',
    [address1.name]: '',
    [address2.name]: '',
    [country.name]: '',
    [mobile.name]: '',
    [countrycode.name]: '',
    [state.name]: '',
    [file.name]: null,
    [file2.name]: null,
    [file3.name]: null,
    [choose.name]: '',
    [terms.name]: false,
[licence.name]:'',
    [date.name]: '',

  };